In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
accident = pd.read_csv('Dataset//accident_data.csv')

In [4]:
accident.describe()

            Latitude      Longitude  Number_of_Casualties  Number_of_Vehicles
count  660654.000000  660653.000000         660679.000000       660679.000000
mean       52.553866      -1.431210              1.357040            1.831255
std         1.406922       1.383330              0.824847            0.715269
min        49.914430      -7.516225              1.000000            1.000000
25%        51.490690      -2.332291              1.000000            1.000000
50%        52.315641      -1.411667              1.000000            2.000000
75%        53.453452      -0.232869              1.000000            2.000000
max        60.757544       1.762010             68.000000           32.000000

In [5]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660679 entries, 0 to 660678
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Index                    660679 non-null  object
 1   Accident_Severity        660679 non-null  object
 2   Accident Date            660679 non-null  object
 3   Latitude                 660654 non-null  float64
 4   Light_Conditions         660679 non-null  object
 5   District Area            660679 non-null  object
 6   Longitude                660653 non-null  float64
 7   Number_of_Casualties     660679 non-null  int64
 8   Number_of_Vehicles       660679 non-null  int64
 9   Road_Surface_Conditions  659953 non-null  object
 10  Road_Type                656159 non-null  object
 11  Urban_or_Rural_Area      660664 non-null  object
 12  Weather_Conditions       646551 non-null  object
 13  Vehicle_Type             660679 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 70.6+ MB

In [6]:
accident.isnull().sum()

Index                          0
Accident_Severity              0
Accident Date                  0
Latitude                      25
Light_Conditions               0
District Area                  0
Longitude                     26
Number_of_Casualties           0
Number_of_Vehicles             0
Road_Surface_Conditions      726
Road_Type                   4520
Urban_or_Rural_Area           15
Weather_Conditions         14128
Vehicle_Type                   0
dtype: int64

In [7]:
accident['Urban_or_Rural_Area'] = accident['Urban_or_Rural_Area'].fillna(accident['Urban_or_Rural_Area'].mode()[0])

In [8]:
accident['Road_Surface_Conditions'] = accident['Road_Surface_Conditions'].fillna(accident['Road_Surface_Conditions'].mode()[0])

In [9]:
accident['Road_Type'] = accident['Road_Type'].fillna(accident['Road_Type'].mode()[0])

In [10]:
accident['Longitude'] = accident['Longitude'].fillna(accident['Longitude'].mean())

In [11]:
accident['Latitude'] = accident['Latitude'].fillna(accident['Latitude'].mean())

In [12]:
accident.isnull().sum()

Index                          0
Accident_Severity              0
Accident Date                  0
Latitude                       0
Light_Conditions               0
District Area                  0
Longitude                      0
Number_of_Casualties           0
Number_of_Vehicles             0
Road_Surface_Conditions        0
Road_Type                      0
Urban_or_Rural_Area            0
Weather_Conditions         14128
Vehicle_Type                   0
dtype: int64

In [13]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660679 entries, 0 to 660678
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Index                    660679 non-null  object
 1   Accident_Severity        660679 non-null  object
 2   Accident Date            660679 non-null  object
 3   Latitude                 660679 non-null  float64
 4   Light_Conditions         660679 non-null  object
 5   District Area            660679 non-null  object
 6   Longitude                660679 non-null  float64
 7   Number_of_Casualties     660679 non-null  int64
 8   Number_of_Vehicles       660679 non-null  int64
 9   Road_Surface_Conditions  660679 non-null  object
 10  Road_Type                660679 non-null  object
 11  Urban_or_Rural_Area      660679 non-null  object
 12  Weather_Conditions       646551 non-null  object
 13  Vehicle_Type             660679 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 70.6+ MB

In [14]:
accident.dtypes

Index                       object
Accident_Severity           object
Accident Date               object
Latitude                   float64
Light_Conditions            object
District Area               object
Longitude                  float64
Number_of_Casualties         int64
Number_of_Vehicles           int64
Road_Surface_Conditions     object
Road_Type                   object
Urban_or_Rural_Area         object
Weather_Conditions          object
Vehicle_Type                object
dtype: object

In [15]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'], dayfirst = True, errors = 'coerce')

In [16]:
accident.dtypes

Index                              object
Accident_Severity                  object
Accident Date              datetime64[ns]
Latitude                          float64
Light_Conditions                   object
District Area                      object
Longitude                         float64
Number_of_Casualties                int64
Number_of_Vehicles                  int64
Road_Surface_Conditions            object
Road_Type                          object
Urban_or_Rural_Area                object
Weather_Conditions                 object
Vehicle_Type                       object
dtype: object

In [17]:
categorical_columns = [
    'Accident_Severity', 'Light_Conditions', 'District Area', 
    'Road_Surface_Conditions', 'Road_Type', 'Urban_or_Rural_Area', 
    'Weather_Conditions', 'Vehicle_Type'
]

for col in categorical_columns:
    accident[col] = accident[col].astype('category')

# Check the data types again
print(accident.dtypes)

Index                              object
Accident_Severity                category
Accident Date              datetime64[ns]
Latitude                          float64
Light_Conditions                 category
District Area                    category
Longitude                         float64
Number_of_Casualties                int64
Number_of_Vehicles                  int64
Road_Surface_Conditions          category
Road_Type                        category
Urban_or_Rural_Area              category
Weather_Conditions               category
Vehicle_Type                     category
dtype: object

In [18]:
accident

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,2019-06-05,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,2019-07-02,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,NaT,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,Single carriageway,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,NaT,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,2019-09-03,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,Single carriageway,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660674,201091NM01760,Slight,NaT,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car
660675,201091NM01881,Slight,NaT,57.232273,Darkness - no lighting,Highland,-3.809281,1,1,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660676,201091NM01935,Slight,NaT,57.585044,Daylight,Highland,-3.862727,1,3,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660677,201091NM01964,Serious,NaT,57.214898,Darkness - no lighting,Highland,-3.823997,1,2,Wet or damp,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
660678,201091NM02142,Serious,NaT,57.575210,Daylight,Highland,-3.895673,1,1,Wet or damp,Dual carriageway,Rural,Snowing no high winds,Car

<h1>MAKE INSTANCES</h1>

<H1>UNIVARIATE</H1>

<h1>1 .WHAT IS THE TOTAL NUMBER OF ACCIDENTS IN EACH SEVERITY?</h1>

<H2>Insight 1. There is a total of 563,801 slight accidents</H2>
<h2>Insight 2. There is a total of 88,217 Serious accidents</h2>
<h2>Insight 3. There is a total of 8,661 Fatal accidents</h2>

In [19]:
(accident['Accident_Severity'].value_counts())

Accident_Severity
Slight     563801
Serious     88217
Fatal        8661
Name: count, dtype: int64

<H1>2.WHAT IS THE PERCENTAGE OF ACCIDENT SEVERITY IN 2019?</H1>

In [20]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'])
accident['Year'] = accident['Accident Date'].dt.year
accident_2019 = accident[accident['Year'] == 2019]
severity_percentage_2019 = accident_2019['Accident_Severity'].value_counts(normalize=True) * 100
severity_percentage_2019 = np.round(severity_percentage_2019, 2)
(severity_percentage_2019)

Accident_Severity
Slight     84.78
Serious    13.67
Fatal       1.55
Name: proportion, dtype: float64

<H2>Insight 4. There is 84.78% percent of slight accidents in 2019 followed by 13.67% of serious accidents and 1.55% of fatal accidents</H2>

<H1>3. WHAT IS THE PERCENTAGE OF accident SEVERITY IN 2020?</H1>

In [21]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'])
accident['Year'] = accident['Accident Date'].dt.year
accident_2020 = accident[accident['Year'] == 2020]
severity_percentage_2020 = accident_2020['Accident_Severity'].value_counts(normalize=True) * 100
severity_percentage_2020 = np.round(severity_percentage_2020, 2)
(severity_percentage_2020)

Accident_Severity
Slight     85.34
Serious    13.32
Fatal       1.34
Name: proportion, dtype: float64

<H2>Insight 5. There is 85.34% percent of slight accidents in 2020 followed by 13.32% of serious accidents and 1.34% of fatal accidents</H2>

<H1>4. WHAT IS THE PERCENTAGE OF ACCIDENT SEVERITY IN 2021?</H1>

In [22]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'])
accident['Year'] = accident['Accident Date'].dt.year
accident_2021 = accident[accident['Year'] == 2021]
severity_percentage_2021 = accident_2021['Accident_Severity'].value_counts(normalize=True) * 100
severity_percentage_2021 = np.round(severity_percentage_2021, 2)
(severity_percentage_2021)

Accident_Severity
Slight     85.37
Serious    13.39
Fatal       1.24
Name: proportion, dtype: float64

<H2>Insight 6. There is 85.37% percent of slight accidents in 2021 followed by 13.39% of serious accidents and 1.24% of fatal accidents</H2>

<h1>5. DOES FATALITY OF ACCIDENT LESSEN EACH YEAR?</h1>

<H2>Insight No. 7 BASED ON THE DATA FROM YEARS 2019-2021 THE PERCENTAGE OF FATALITY DROP FROM 1.55% TO 1.24% SHOWING THAT FATALITY LESSEN EVERY YEAR</H2>

<H1>6. WHAT IS THE PERCENTAGE OF SEVERITY IN 2022?</H1>

In [30]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'])
accident['Year'] = accident['Accident Date'].dt.year
accident_2022 = accident[accident['Year'] == 2022]
severity_percentage_2022 = accident_2022['Accident_Severity'].value_counts(normalize=True) * 100
severity_percentage_2022 = np.round(severity_percentage_2022, 2)
(severity_percentage_2022)

Accident_Severity
Slight     86.11
Serious    12.79
Fatal       1.10
Name: proportion, dtype: float64

<H2>Insight 8. There is 86.11% percent of slight accidents in 2022 followed by 12.79% of serious accidents and 1.10% of fatal accidents</H2>

<H1>BIVARIATE</H1>

<h1>7. WHAT VEHICLE HAS THE MOST FATAL SEVERITY ACCIDENT?</h1>

In [24]:
fatal_accidents_percentage = accident[accident['Accident_Severity'] == 'Fatal'] \
    .groupby('Vehicle_Type').size() / accident.groupby('Vehicle_Type').size() * 100
fatal_accidents_percentage = np.round(fatal_accidents_percentage, 2)
(fatal_accidents_percentage)

Vehicle_Type
Agricultural vehicle                     1.08
Bus or coach (17 or more pass seats)     1.26
Car                                      1.32
Data missing or out of range             0.00
Goods 7.5 tonnes mgw and over            1.25
Goods over 3.5t. and under 7.5t          1.10
Minibus (8 - 16 passenger seats)         1.47
Motorcycle 125cc and under               1.24
Motorcycle 50cc and under                1.25
Motorcycle over 125cc and up to 500cc    1.37
Motorcycle over 500cc                    1.32
Other vehicle                            1.24
Pedal cycle                              3.05
Ridden horse                             0.00
Taxi/Private hire car                    1.17
Van / Goods 3.5 tonnes mgw or under      1.37
dtype: float64

<H2>Insight 9. PEDAL CYCLE HAS MOST PERCENTAGE OF FATAL ACCIDENTS WITH 3.05%</H2>

<h1>8. WHAT VEHICLE HAS THE MOST SERIOUS SEVERITY ACCIDENT?</h1>

In [25]:
fatal_accidents_percentage = accident[accident['Accident_Severity'] == 'Serious'] \
    .groupby('Vehicle_Type').size() / accident.groupby('Vehicle_Type').size() * 100
fatal_accidents_percentage = np.round(fatal_accidents_percentage, 2)
(fatal_accidents_percentage)

Vehicle_Type
Agricultural vehicle                     14.48
Bus or coach (17 or more pass seats)     13.03
Car                                      13.35
Data missing or out of range              0.00
Goods 7.5 tonnes mgw and over            13.41
Goods over 3.5t. and under 7.5t          14.06
Minibus (8 - 16 passenger seats)         13.97
Motorcycle 125cc and under               13.30
Motorcycle 50cc and under                13.34
Motorcycle over 125cc and up to 500cc    13.24
Motorcycle over 500cc                    13.47
Other vehicle                            13.61
Pedal cycle                              19.80
Ridden horse                              0.00
Taxi/Private hire car                    13.32
Van / Goods 3.5 tonnes mgw or under      13.33
dtype: float64

<H2>Insight 10. PEDAL CYCLE HAS MOST PERCENTAGE OF SERIOUS ACCIDENTS WITH 19.80%</H2>

<h1>9. WHAT VEHICLE HAS THE MOST SLIGHT SEVERITY ACCIDENT?</h1>

In [26]:
fatal_accidents_percentage = accident[accident['Accident_Severity'] == 'Slight'] \
    .groupby('Vehicle_Type').size() / accident.groupby('Vehicle_Type').size() * 100
fatal_accidents_percentage = np.round(fatal_accidents_percentage, 2)
(fatal_accidents_percentage)

Vehicle_Type
Agricultural vehicle                      84.44
Bus or coach (17 or more pass seats)      85.71
Car                                       85.33
Data missing or out of range             100.00
Goods 7.5 tonnes mgw and over             85.34
Goods over 3.5t. and under 7.5t           84.84
Minibus (8 - 16 passenger seats)          84.56
Motorcycle 125cc and under                85.46
Motorcycle 50cc and under                 85.41
Motorcycle over 125cc and up to 500cc     85.38
Motorcycle over 500cc                     85.20
Other vehicle                             85.15
Pedal cycle                               77.16
Ridden horse                             100.00
Taxi/Private hire car                     85.51
Van / Goods 3.5 tonnes mgw or under       85.30
dtype: float64

<H2>Insight 11. Bus or coach (17 or more pass seats) HAS MOST PERCENTAGE OF SLIGHT ACCIDENTS WITH 85.71% FOLLOWED BY TAXI/PRIVATE HIRE CAR WITH 85.51%"</H2>

<H1>10.DOES ROAD TYPE AFFECTS THE SEVERITY OF ACCIDENTS</H1>

In [27]:
severity_by_road_type = accident.groupby(['Road_Type', 'Accident_Severity']).size()
severity_by_road_type_percentage = severity_by_road_type / severity_by_road_type.groupby('Road_Type').transform('sum') * 100
severity_by_road_type_percentage = np.round(severity_by_road_type_percentage, 2)
(severity_by_road_type_percentage)

Road_Type           Accident_Severity
Dual carriageway    Fatal                 1.83
                    Serious              11.81
                    Slight               86.36
One way street      Fatal                 0.70
                    Serious              12.21
                    Slight               87.09
Roundabout          Fatal                 0.32
                    Serious               8.33
                    Slight               91.35
Single carriageway  Fatal                 1.32
                    Serious              14.20
                    Slight               84.48
Slip road           Fatal                 0.70
                    Serious               8.68
                    Slight               90.63
dtype: float64

<h2>Insight 12. Single carriage and Dual Carriage way has the most Fatal Accident Severity </h2>

<h1>11.WHAT ROAD TYPE HAS THE SLIGHTEST ACCIDENT SEVERITY?</h1>

<H2>Insight 13. ROUNDABOUT HAS MOST PERCENTAGE OF SLIGHTEST ACCIDENT SEVERITY WITH 91.35%</H2>

<h1>12.WHAT ROAD TYPE HAS THE MOST SERIOUS ACCIDENT SEVERITY?</h1>

<H2>Insight 14. SINGLE CARRIEGEWAY HAS MOST PERCENTAGE OF SERIOUS ACCIDENT SEVERITY WITH 14.20%</H2>

<h1>13. WHAT ROAD TYPE HAS THE MOST FATAL ACCIDENT SEVERITY?</h1>

<H2>Insight 15. DUAL CARRIAGEWAY HAS MOST PERCENTAGE OF FATAL ACCIDENT SEVERITY WITH 1.83%</H2

<H1>14. DOES LIGHT CONDITION AFFECTS ACCIDENT SEVERITY</H1>

In [35]:
light_severity_counts = accident.groupby(['Light_Conditions', 'Accident_Severity']).size().reset_index(name='Count')
(light_severity_counts)

               Light_Conditions Accident_Severity   Count
0   Darkness - lighting unknown             Fatal      68
1   Darkness - lighting unknown           Serious     794
2   Darkness - lighting unknown            Slight    5622
3         Darkness - lights lit             Fatal    1860
4         Darkness - lights lit           Serious   19130
5         Darkness - lights lit            Slight  108345
6       Darkness - lights unlit             Fatal      45
7       Darkness - lights unlit           Serious     360
8       Darkness - lights unlit            Slight    2138
9        Darkness - no lighting             Fatal    1612
10       Darkness - no lighting           Serious    7174
11       Darkness - no lighting            Slight   28651
12                     Daylight             Fatal    5076
13                     Daylight           Serious   60759
14                     Daylight            Slight  419045

<H2>Insight 16. From the data that we have gathered we've seen that the light conditions has impact on the severity of accidents</H2

In [38]:
light_severity_counts = accident.groupby(['Light_Conditions', 'Accident_Severity']).size().reset_index(name='Count')
total_by_light = light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum')
light_severity_counts['Percentage'] = (light_severity_counts['Count'] / total_by_light) * 100
light_severity_counts = np.round(light_severity_counts, 2)
(light_severity_counts)

               Light_Conditions Accident_Severity   Count  Percentage
0   Darkness - lighting unknown             Fatal      68        1.05
1   Darkness - lighting unknown           Serious     794       12.25
2   Darkness - lighting unknown            Slight    5622       86.71
3         Darkness - lights lit             Fatal    1860        1.44
4         Darkness - lights lit           Serious   19130       14.79
5         Darkness - lights lit            Slight  108345       83.77
6       Darkness - lights unlit             Fatal      45        1.77
7       Darkness - lights unlit           Serious     360       14.16
8       Darkness - lights unlit            Slight    2138       84.07
9        Darkness - no lighting             Fatal    1612        4.31
10       Darkness - no lighting           Serious    7174       19.16
11       Darkness - no lighting            Slight   28651       76.53
12                     Daylight             Fatal    5076        1.05
13                     Daylight           Serious   60759       12.53
14                     Daylight            Slight  419045       86.42

<H2>Insight 17. Contrary to the saying that in Darkness there are more severe accidents we saw from the data that in Daylight there are more sever accidents with the total of 5076</H2

<H2>Insight 18. If we based on the percentage of the one with highest fatality we will see that Darkness - no lighting has the highest percentage of 4.31% </H2

<H2>Insight 19. If we based on the percentage of the one with the most serious severity we will see that Darkness - no lighting has the highest percentage of 19.16%</H2

<H2>Insight 20. If we based on the percentage of the one with slightest accident severity we will see that Darkness - lighting unknown has the highest percentage of 86.71% </H2

In [51]:
light_severity_counts = accident[['Light_Conditions', 'Accident_Severity']].value_counts().reset_index(name='Count')
light_severity_counts['Percentage'] = light_severity_counts['Count'] / light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum') * 100
light_severity_counts = np.round(light_severity_counts, 2)
Darklightunk_severity = light_severity_counts[light_severity_counts['Light_Conditions'] == 'Darkness - lighting unknown']
(Darklightunk_severity)

               Light_Conditions Accident_Severity  Count  Percentage
6   Darkness - lighting unknown            Slight   5622       86.71
11  Darkness - lighting unknown           Serious    794       12.25
13  Darkness - lighting unknown             Fatal     68        1.05

In [55]:
light_severity_counts = accident[['Light_Conditions', 'Accident_Severity']].value_counts().reset_index(name='Count')
light_severity_counts['Percentage'] = light_severity_counts['Count'] / light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum') * 100
light_severity_counts = np.round(light_severity_counts, 2)
Darklightlit_severity = light_severity_counts[light_severity_counts['Light_Conditions'] == 'Darkness - lights lit']
(Darklightlit_severity)

          Light_Conditions Accident_Severity  Count  Percentage
3   Darkness - no lighting            Slight  28651       76.53
5   Darkness - no lighting           Serious   7174       19.16
10  Darkness - no lighting             Fatal   1612        4.31

In [54]:
light_severity_counts = accident[['Light_Conditions', 'Accident_Severity']].value_counts().reset_index(name='Count')
light_severity_counts['Percentage'] = light_severity_counts['Count'] / light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum') * 100
light_severity_counts = np.round(light_severity_counts, 2)
Darklightunlit_severity = light_severity_counts[light_severity_counts['Light_Conditions'] == 'Darkness - lights unlit']
(Darklightunlit_severity)

           Light_Conditions Accident_Severity  Count  Percentage
8   Darkness - lights unlit            Slight   2138       84.07
12  Darkness - lights unlit           Serious    360       14.16
14  Darkness - lights unlit             Fatal     45        1.77

In [56]:
light_severity_counts = accident[['Light_Conditions', 'Accident_Severity']].value_counts().reset_index(name='Count')
light_severity_counts['Percentage'] = light_severity_counts['Count'] / light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum') * 100
light_severity_counts = np.round(light_severity_counts, 2)
Darknolight_severity = light_severity_counts[light_severity_counts['Light_Conditions'] == 'Darkness - no lighting']
(Darknolight_severity)

          Light_Conditions Accident_Severity  Count  Percentage
3   Darkness - no lighting            Slight  28651       76.53
5   Darkness - no lighting           Serious   7174       19.16
10  Darkness - no lighting             Fatal   1612        4.31

In [49]:
light_severity_counts = accident[['Light_Conditions', 'Accident_Severity']].value_counts().reset_index(name='Count')
light_severity_counts['Percentage'] = light_severity_counts['Count'] / light_severity_counts.groupby('Light_Conditions')['Count'].transform('sum') * 100
light_severity_counts = np.round(light_severity_counts, 2)
Daylight_severity = light_severity_counts[light_severity_counts['Light_Conditions'] == 'Daylight']
(Daylight_severity)

  Light_Conditions Accident_Severity   Count  Percentage
0         Daylight            Slight  419045       86.42
2         Daylight           Serious   60759       12.53
7         Daylight             Fatal    5076        1.05

<H1>MULTI-VARIATE</H1>

<h1>14. How does the type of road and the type of vehicle influence the severity of accidents?</h1>

In [31]:
severity_by_road_vehicle = accident.groupby(['Road_Type', 'Vehicle_Type', 'Accident_Severity']).size().reset_index(name='Accident_Count')
(severity_by_road_vehicle)

,Road_Type,Vehicle_Type,Accident_Severity,Accident_Count
0,Dual carriageway,Agricultural vehicle,Fatal,6
1,Dual carriageway,Agricultural vehicle,Serious,37
2,Dual carriageway,Agricultural vehicle,Slight,250
3,Dual carriageway,Bus or coach (17 or more pass seats),Fatal,63
4,Dual carriageway,Bus or coach (17 or more pass seats),Serious,489
5,Dual carriageway,Bus or coach (17 or more pass seats),Slight,3491
6,Dual carriageway,Car,Fatal,1364
7,Dual carriageway,Car,Serious,8833
8,Dual carriageway,Car,Slight,64623
9,Dual carriageway,Data missing or out of range,Fatal,0
10,Dual carriageway,Data missing or out of range,Serious,0
11,Dual carriageway,Data missing or out of range,Slight,1
12,Dual carriageway,Goods 7.5 tonnes mgw and over,Fatal,49
13,Dual carriageway,Goods 7.5 tonnes mgw and over,Serious,289
14,Dual carriageway,Goods 7.5 tonnes mgw and over,Slight,2293
15,Dual carriageway,Goods over 3.5t. and under 7.5t,Fatal,13
16,Dual carriageway,Goods over 3.5t. and under 7.5t,Serious,113
17,Dual carriageway,Goods over 3.5t. and under 7.5t,Slight,833
18,Dual carriageway,Minibus (8 - 16 passenger seats),Fatal,5
19,Dual carriageway,Minibus (8 - 16 passenger seats),Serious,33
20,Dual carriageway,Minibus (8 - 16 passenger seats),Slight,237
21,Dual carriageway,Motorcycle 125cc and under,Fatal,33
22,Dual carriageway,Motorcycle 125cc and under,Serious,275
23,Dual carriageway,Motorcycle 125cc and under,Slight,1920
24,Dual carriageway,Motorcycle 50cc and under,Fatal,23
25,Dual carriageway,Motorcycle 50cc and under,Serious,127
26,Dual carriageway,Motorcycle 50cc and under,Slight,935
27,Dual carriageway,Motorcycle over 125cc and up to 500cc,Fatal,22
28,Dual carriageway,Motorcycle over 125cc and up to 500cc,Serious,133
29,Dual carriageway,Motorcycle over 125cc and up to 500cc,Slight,1055
30,Dual carriageway,Motorcycle over 500cc,Fatal,82
31,Dual carriageway,Motorcycle over 500cc,Serious,463
32,Dual carriageway,Motorcycle over 500cc,Slight,3385
33,Dual carriageway,Other vehicle,Fatal,14
34,Dual carriageway,Other vehicle,Serious,98
35,Dual carriageway,Other vehicle,Slight,723
36,Dual carriageway,Pedal cycle,Fatal,1
37,Dual carriageway,Pedal cycle,Serious,7
38,Dual carriageway,Pedal cycle,Slight,26
39,Dual carriageway,Ridden horse,Fatal,0
40,Dual carriageway,Ridden horse,Serious,0
41,Dual carriageway,Ridden horse,Slight,0
42,Dual carriageway,Taxi/Private hire car,Fatal,37
43,Dual carriageway,Taxi/Private hire car,Serious,236
44,Dual carriageway,Taxi/Private hire car,Slight,1700
45,Dual carriageway,Van / Goods 3.5 tonnes mgw or under,Fatal,103
46,Dual carriageway,Van / Goods 3.5 tonnes mgw or under,Serious,613
47,Dual carriageway,Van / Goods 3.5 tonnes mgw or under,Slight,4391
48,One way street,Agricultural vehicle,Fatal,1
49,One way street,Agricultural vehicle,Serious,6
50,One way street,Agricultural vehicle,Slight,42
51,One way street,Bus or coach (17 or more pass seats),Fatal,2
52,One way street,Bus or coach (17 or more pass seats),Serious,75
53,One way street,Bus or coach (17 or more pass seats),Slight,469
54,One way street,Car,Fatal,69
55,One way street,Car,Serious,1216
56,One way street,Car,Slight,8938
57,One way street,Data missing or out of range,Fatal,0
58,One way street,Data missing or out of range,Serious,0
59,One way street,Data missing or out of range,Slight,0
60,One way street,Goods 7.5 tonnes mgw and over,Fatal,3
61,One way street,Goods 7.5 tonnes mgw and over,Serious,45
62,One way street,Goods 7.5 tonnes mgw and over,Slight,293
63,One way street,Goods over 3.5t. and under 7.5t,Fatal,4
64,One way street,Goods over 3.5t. and under 7.5t,Serious,10
65,One way street,Goods over 3.5t. and under 7.5t,Slight,102
66,One way street,Minibus (8 - 16 passenger seats),Fatal,0
67,One way street,Minibus (8 - 16 passenger seats),Serious,11
68,One way street,Minibus (8 - 16 passenger seats),Slight,29
69,One way street,Motorcycle 125cc and under,Fatal,2
70,One way street,Motorcycle 125cc and under,Serious,38
71,One way street,Motorcycle 125cc and under,Slight,267
72,One way street,Motorcycle 50cc and under,Fatal,4
73,One way street,Motorcycle 50cc and under,Serious,18
74,One way street,Motorcycle 50cc and under,Slight,111
75,One way street,Motorcycle over 125cc and up to 500cc,Fatal,0
76,One way street,Motorcycle over 125cc and up to 500cc,Serious,12
77,One way street,Motorcycle over 125cc and up to 500cc,Slight,142
78,One way street,Motorcycle over 500cc,Fatal,4
79,One way street,Motorcycle over 500cc,Serious,79
80,One way street,Motorcycle over 500cc,Slight,416
81,One way street,Other vehicle,Fatal,1
82,One way street,Other vehicle,Serious,12
83,One way street,Other vehicle,Slight,117
84,One way street,Pedal cycle,Fatal,0
85,One way street,Pedal cycle,Serious,0
86,One way street,Pedal cycle,Slight,4
87,One way street,Ridden horse,Fatal,0
88,One way street,Ridden horse,Serious,0
89,One way street,Ridden horse,Slight,0
90,One way street,Taxi/Private hire car,Fatal,1
91,One way street,Taxi/Private hire car,Serious,37
92,One way street,Taxi/Private hire car,Slight,256
93,One way street,Van / Goods 3.5 tonnes mgw or under,Fatal,4
94,One way street,Van / Goods 3.5 tonnes mgw or under,Serious,96
95,One way street,Van / Goods 3.5 tonnes mgw or under,Slight,623
96,Roundabout,Agricultural vehicle,Fatal,0
97,Roundabout,Agricultural vehicle,Serious,8
98,Roundabout,Agricultural vehicle,Slight,121
99,Roundabout,Bus or coach (17 or more pass seats),Fatal,6
100,Roundabout,Bus or coach (17 or more pass seats),Serious,119
101,Roundabout,Bus or coach (17 or more pass seats),Slight,1579
102,Roundabout,Car,Fatal,109
103,Roundabout,Car,Serious,2782
104,Roundabout,Car,Slight,30296
105,Roundabout,Data missing or out of range,Fatal,0
106,Roundabout,Data missing or out of range,Serious,0
107,Roundabout,Data missing or out of range,Slight,0
108,Roundabout,Goods 7.5 tonnes mgw and over,Fatal,4
109,Roundabout,Goods 7.5 tonnes mgw and over,Serious,90
110,Roundabout,Goods 7.5 tonnes mgw and over,Slight,1016
111,Roundabout,Goods over 3.5t. and under 7.5t,Fatal,0
112,Roundabout,Goods over 3.5t. and under 7.5t,Serious,36
113,Roundabout,Goods over 3.5t. and under 7.5t,Slight,386
114,Roundabout,Minibus (8 - 16 passenger seats),Fatal,0
115,Roundabout,Minibus (8 - 16 passenger seats),Serious,9
116,Roundabout,Minibus (8 - 16 passenger seats),Slight,129
117,Roundabout,Motorcycle 125cc and under,Fatal,3
118,Roundabout,Motorcycle 125cc and under,Serious,88
119,Roundabout,Motorcycle 125cc and under,Slight,900
120,Roundabout,Motorcycle 50cc and under,Fatal,0
121,Roundabout,Motorcycle 50cc and under,Serious,41
122,Roundabout,Motorcycle 50cc and under,Slight,471
123,Roundabout,Motorcycle over 125cc and up to 500cc,Fatal,5
124,Roundabout,Motorcycle over 125cc and up to 500cc,Serious,36
125,Roundabout,Motorcycle over 125cc and up to 500cc,Slight,452
126,Roundabout,Motorcycle over 500cc,Fatal,4
127,Roundabout,Motorcycle over 500cc,Serious,149
128,Roundabout,Motorcycle over 500cc,Slight,1584
129,Roundabout,Other vehicle,Fatal,1
130,Roundabout,Other vehicle,Serious,36
131,Roundabout,Other vehicle,Slight,349
132,Roundabout,Pedal cycle,Fatal,0
133,Roundabout,Pedal cycle,Serious,2
134,Roundabout,Pedal cycle,Slight,14
135,Roundabout,Ridden horse,Fatal,0
136,Roundabout,Ridden horse,Serious,0
137,Roundabout,Ridden horse,Slight,0
138,Roundabout,Taxi/Private hire car,Fatal,2
139,Roundabout,Taxi/Private hire car,Serious,64
140,Roundabout,Taxi/Private hire car,Slight,807
141,Roundabout,Van / Goods 3.5 tonnes mgw or under,Fatal,8
142,Roundabout,Van / Goods 3.5 tonnes mgw or under,Serious,205
143,Roundabout,Van / Goods 3.5 tonnes mgw or under,Slight,2081
144,Single carriageway,Agricultural vehicle,Fatal,14
145,Single carriageway,Agricultural vehicle,Serious,228
146,Single carriageway,Agricultural vehicle,Slight,1207
147,Single carriageway,Bus or coach (17 or more pass seats),Fatal,251
148,Single carriageway,Bus or coach (17 or more pass seats),Serious,2661
149,Single carriageway,Bus or coach (17 or more pass seats),Slight,16388
150,Single carriageway,Car,Fatal,5002
151,Single carriageway,Car,Serious,53172
152,Single carriageway,Car,Slight,316290
153,Single carriageway,Data missing or out of range,Fatal,0
154,Single carriageway,Data missing or out of range,Serious,0
155,Single carriageway,Data missing or out of range,Slight,5
156,Single carriageway,Goods 7.5 tonnes mgw and over,Fatal,158
157,Single carriageway,Goods 7.5 tonnes mgw and over,Serious,1882
158,Single carriageway,Goods 7.5 tonnes mgw and over,Slight,10997
159,Single carriageway,Goods over 3.5t. and under 7.5t,Fatal,49
160,Single carriageway,Goods over 3.5t. and under 7.5t,Serious,698
161,Single carriageway,Goods over 3.5t. and under 7.5t,Slight,3794
162,Single carriageway,Minibus (8 - 16 passenger seats),Fatal,24
163,Single carriageway,Minibus (8 - 16 passenger seats),Serious,222
164,Single carriageway,Minibus (8 - 16 passenger seats),Slight,1261
165,Single carriageway,Motorcycle 125cc and under,Fatal,150
166,Single carriageway,Motorcycle 125cc and under,Serious,1619
167,Single carriageway,Motorcycle 125cc and under,Slight,9827
168,Single carriageway,Motorcycle 50cc and under,Fatal,68
169,Single carriageway,Motorcycle 50cc and under,Serious,820
170,Single carriageway,Motorcycle 50cc and under,Slight,4896
171,Single carriageway,Motorcycle over 125cc and up to 500cc,Fatal,78
172,Single carriageway,Motorcycle over 125cc and up to 500cc,Serious,824
173,Single carriageway,Motorcycle over 125cc and up to 500cc,Slight,4799
174,Single carriageway,Motorcycle over 500cc,Fatal,247
175,Single carriageway,Motorcycle over 500cc,Serious,2746
176,Single carriageway,Motorcycle over 500cc,Slight,16214
177,Single carriageway,Other vehicle,Fatal,53
178,Single carriageway,Other vehicle,Serious,612
179,Single carriageway,Other vehicle,Slight,3557
180,Single carriageway,Pedal cycle,Fatal,5
181,Single carriageway,Pedal cycle,Serious,30
182,Single carriageway,Pedal cycle,Slight,106
183,Single carriageway,Ridden horse,Fatal,0
184,Single carriageway,Ridden horse,Serious,0
185,Single carriageway,Ridden horse,Slight,4
186,Single carriageway,Taxi/Private hire car,Fatal,115
187,Single carriageway,Taxi/Private hire car,Serious,1413
188,Single carriageway,Taxi/Private hire car,Slight,8502
189,Single carriageway,Van / Goods 3.5 tonnes mgw or under,Fatal,346
190,Single carriageway,Van / Goods 3.5 tonnes mgw or under,Serious,3613
191,Single carriageway,Van / Goods 3.5 tonnes mgw or under,Slight,21716
192,Slip road,Agricultural vehicle,Fatal,0
193,Slip road,Agricultural vehicle,Serious,3
194,Slip road,Agricultural vehicle,Slight,24
195,Slip road,Bus or coach (17 or more pass seats),Fatal,3
196,Slip road,Bus or coach (17 or more pass seats),Serious,29
197,Slip road,Bus or coach (17 or more pass seats),Slight,253
198,Slip road,Car,Fatal,33
199,Slip road,Car,Serious,458
200,Slip road,Car,Slight,4807
201,Slip road,Data missing or out of range,Fatal,0
202,Slip road,Data missing or out of range,Serious,0
203,Slip road,Data missing or out of range,Slight,0
204,Slip road,Goods 7.5 tonnes mgw and over,Fatal,2
205,Slip road,Goods 7.5 tonnes mgw and over,Serious,15
206,Slip road,Goods 7.5 tonnes mgw and over,Slight,171
207,Slip road,Goods over 3.5t. and under 7.5t,Fatal,1
208,Slip road,Goods over 3.5t. and under 7.5t,Serious,0
209,Slip road,Goods over 3.5t. and under 7.5t,Slight,57
210,Slip road,Minibus (8 - 16 passenger seats),Fatal,0
211,Slip road,Minibus (8 - 16 passenger seats),Serious,1
212,Slip road,Minibus (8 - 16 passenger seats),Slight,15
213,Slip road,Motorcycle 125cc and under,Fatal,1
214,Slip road,Motorcycle 125cc and under,Serious,11
215,Slip road,Motorcycle 125cc and under,Slight,135
216,Slip road,Motorcycle 50cc and under,Fatal,0
217,Slip road,Motorcycle 50cc and under,Serious,8
218,Slip road,Motorcycle 50cc and under,Slight,81
219,Slip road,Motorcycle over 125cc and up to 500cc,Fatal,0
220,Slip road,Motorcycle over 125cc and up to 500cc,Serious,9
221,Slip road,Motorcycle over 125cc and up to 500cc,Slight,89
222,Slip road,Motorcycle over 500cc,Fatal,2
223,Slip road,Motorcycle over 500cc,Serious,20
224,Slip road,Motorcycle over 500cc,Slight,262
225,Slip road,Other vehicle,Fatal,1
226,Slip road,Other vehicle,Serious,9
227,Slip road,Other vehicle,Slight,54
228,Slip road,Pedal cycle,Fatal,0
229,Slip road,Pedal cycle,Serious,0
230,Slip road,Pedal cycle,Slight,2
231,Slip road,Ridden horse,Fatal,0
232,Slip road,Ridden horse,Serious,0
233,Slip road,Ridden horse,Slight,0
234,Slip road,Taxi/Private hire car,Fatal,0
235,Slip road,Taxi/Private hire car,Serious,21
236,Slip road,Taxi/Private hire car,Slight,103
237,Slip road,Van / Goods 3.5 tonnes mgw or under,Fatal,6
238,Slip road,Van / Goods 3.5 tonnes mgw or under,Serious,27
239,Slip road,Van / Goods 3.5 tonnes mgw or under,Slight,328

In [32]:
fatal_accidents = severity_by_road_vehicle[severity_by_road_vehicle['Accident_Severity'] == 'Fatal']
total_accidents = severity_by_road_vehicle.groupby(['Road_Type', 'Vehicle_Type'])['Accident_Count'].sum().reset_index(name='Total_Accidents')
fatal_percentage = pd.merge(fatal_accidents, total_accidents, on=['Road_Type', 'Vehicle_Type'])
fatal_percentage['Fatal_Percentage'] = (fatal_percentage['Accident_Count'] / fatal_percentage['Total_Accidents']) * 100
fatal_percentage['Fatal_Percentage'] = fatal_percentage['Fatal_Percentage'].round(2)
(fatal_percentage)

,Road_Type,Vehicle_Type,Accident_Severity,Accident_Count,Total_Accidents,Fatal_Percentage
0,Dual carriageway,Agricultural vehicle,Fatal,6,293,2.05
1,Dual carriageway,Bus or coach (17 or more pass seats),Fatal,63,4043,1.56
2,Dual carriageway,Car,Fatal,1364,74820,1.82
3,Dual carriageway,Data missing or out of range,Fatal,0,1,0.00
4,Dual carriageway,Goods 7.5 tonnes mgw and over,Fatal,49,2631,1.86
5,Dual carriageway,Goods over 3.5t. and under 7.5t,Fatal,13,959,1.36
6,Dual carriageway,Minibus (8 - 16 passenger seats),Fatal,5,275,1.82
7,Dual carriageway,Motorcycle 125cc and under,Fatal,33,2228,1.48
8,Dual carriageway,Motorcycle 50cc and under,Fatal,23,1085,2.12
9,Dual carriageway,Motorcycle over 125cc and up to 500cc,Fatal,22,1210,1.82
10,Dual carriageway,Motorcycle over 500cc,Fatal,82,3930,2.09
11,Dual carriageway,Other vehicle,Fatal,14,835,1.68
12,Dual carriageway,Pedal cycle,Fatal,1,34,2.94
13,Dual carriageway,Ridden horse,Fatal,0,0,NaN
14,Dual carriageway,Taxi/Private hire car,Fatal,37,1973,1.88
15,Dual carriageway,Van / Goods 3.5 tonnes mgw or under,Fatal,103,5107,2.02
16,One way street,Agricultural vehicle,Fatal,1,49,2.04
17,One way street,Bus or coach (17 or more pass seats),Fatal,2,546,0.37
18,One way street,Car,Fatal,69,10223,0.67
19,One way street,Data missing or out of range,Fatal,0,0,NaN
20,One way street,Goods 7.5 tonnes mgw and over,Fatal,3,341,0.88
21,One way street,Goods over 3.5t. and under 7.5t,Fatal,4,116,3.45
22,One way street,Minibus (8 - 16 passenger seats),Fatal,0,40,0.00
23,One way street,Motorcycle 125cc and under,Fatal,2,307,0.65
24,One way street,Motorcycle 50cc and under,Fatal,4,133,3.01
25,One way street,Motorcycle over 125cc and up to 500cc,Fatal,0,154,0.00
26,One way street,Motorcycle over 500cc,Fatal,4,499,0.80
27,One way street,Other vehicle,Fatal,1,130,0.77
28,One way street,Pedal cycle,Fatal,0,4,0.00
29,One way street,Ridden horse,Fatal,0,0,NaN
30,One way street,Taxi/Private hire car,Fatal,1,294,0.34
31,One way street,Van / Goods 3.5 tonnes mgw or under,Fatal,4,723,0.55
32,Roundabout,Agricultural vehicle,Fatal,0,129,0.00
33,Roundabout,Bus or coach (17 or more pass seats),Fatal,6,1704,0.35
34,Roundabout,Car,Fatal,109,33187,0.33
35,Roundabout,Data missing or out of range,Fatal,0,0,NaN
36,Roundabout,Goods 7.5 tonnes mgw and over,Fatal,4,1110,0.36
37,Roundabout,Goods over 3.5t. and under 7.5t,Fatal,0,422,0.00
38,Roundabout,Minibus (8 - 16 passenger seats),Fatal,0,138,0.00
39,Roundabout,Motorcycle 125cc and under,Fatal,3,991,0.30
40,Roundabout,Motorcycle 50cc and under,Fatal,0,512,0.00
41,Roundabout,Motorcycle over 125cc and up to 500cc,Fatal,5,493,1.01
42,Roundabout,Motorcycle over 500cc,Fatal,4,1737,0.23
43,Roundabout,Other vehicle,Fatal,1,386,0.26
44,Roundabout,Pedal cycle,Fatal,0,16,0.00
45,Roundabout,Ridden horse,Fatal,0,0,NaN
46,Roundabout,Taxi/Private hire car,Fatal,2,873,0.23
47,Roundabout,Van / Goods 3.5 tonnes mgw or under,Fatal,8,2294,0.35
48,Single carriageway,Agricultural vehicle,Fatal,14,1449,0.97
49,Single carriageway,Bus or coach (17 or more pass seats),Fatal,251,19300,1.30
50,Single carriageway,Car,Fatal,5002,374464,1.34
51,Single carriageway,Data missing or out of range,Fatal,0,5,0.00
52,Single carriageway,Goods 7.5 tonnes mgw and over,Fatal,158,13037,1.21
53,Single carriageway,Goods over 3.5t. and under 7.5t,Fatal,49,4541,1.08
54,Single carriageway,Minibus (8 - 16 passenger seats),Fatal,24,1507,1.59
55,Single carriageway,Motorcycle 125cc and under,Fatal,150,11596,1.29
56,Single carriageway,Motorcycle 50cc and under,Fatal,68,5784,1.18
57,Single carriageway,Motorcycle over 125cc and up to 500cc,Fatal,78,5701,1.37
58,Single carriageway,Motorcycle over 500cc,Fatal,247,19207,1.29
59,Single carriageway,Other vehicle,Fatal,53,4222,1.26
60,Single carriageway,Pedal cycle,Fatal,5,141,3.55
61,Single carriageway,Ridden horse,Fatal,0,4,0.00
62,Single carriageway,Taxi/Private hire car,Fatal,115,10030,1.15
63,Single carriageway,Van / Goods 3.5 tonnes mgw or under,Fatal,346,25675,1.35
64,Slip road,Agricultural vehicle,Fatal,0,27,0.00
65,Slip road,Bus or coach (17 or more pass seats),Fatal,3,285,1.05
66,Slip road,Car,Fatal,33,5298,0.62
67,Slip road,Data missing or out of range,Fatal,0,0,NaN
68,Slip road,Goods 7.5 tonnes mgw and over,Fatal,2,188,1.06
69,Slip road,Goods over 3.5t. and under 7.5t,Fatal,1,58,1.72
70,Slip road,Minibus (8 - 16 passenger seats),Fatal,0,16,0.00
71,Slip road,Motorcycle 125cc and under,Fatal,1,147,0.68
72,Slip road,Motorcycle 50cc and under,Fatal,0,89,0.00
73,Slip road,Motorcycle over 125cc and up to 500cc,Fatal,0,98,0.00
74,Slip road,Motorcycle over 500cc,Fatal,2,284,0.70
75,Slip road,Other vehicle,Fatal,1,64,1.56
76,Slip road,Pedal cycle,Fatal,0,2,0.00
77,Slip road,Ridden horse,Fatal,0,0,NaN
78,Slip road,Taxi/Private hire car,Fatal,0,124,0.00
79,Slip road,Van / Goods 3.5 tonnes mgw or under,Fatal,6,361,1.66